-- Step 1 create database & table 

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS THERAREBURGER;
USE DATABASE THERAREBURGER;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE MONTHLY_REVENUE (
  "LOCATION_NAME" varchar(50),
  "REGION" varchar2(50),
  "POSTAL_CODE" varchar2(255),
  "STREET_ADDRESS" varchar2(255) ,
  "RAW_TOTAL_SPEND" FLOAT ,
  "RAW_NUM_TRANSACTIONS" number,
  "RAW_NUM_CUSTOMERS" number,
  "ONLINE_SPEND" FLOAT ,
  "MEDIAN_SPEND_PER_TRANSACTION" FLOAT ,
  "MEDIAN_SPEND_PER_CUSTOMER" FLOAT
); 
-----------------------------------------------------------------------
-- Step 2 Load the data by uploading CSV file 
SELECT
  *
FROM
  MONTHLY_REVENUE;
-----------------------------------------------------------------------
-- Step 3 SQL Query 
--- Step 3-1: list the data from Monthly_revenue table
SELECT LOCATION_NAME, REGION, POSTAL_CODE, STREET_ADDRESS, RAW_TOTAL_SPEND, RAW_NUM_TRANSACTIONS, RAW_NUM_CUSTOMERS, ONLINE_SPEND, MEDIAN_SPEND_PER_TRANSACTION, MEDIAN_SPEND_PER_CUSTOMER
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE;


---Step 3-2: find category tags with burger in sample data 
SELECT LOCATION_NAME, REGION, POSTAL_CODE, STREET_ADDRESS, RAW_TOTAL_SPEND, RAW_NUM_TRANSACTIONS, RAW_NUM_CUSTOMERS, ONLINE_SPEND, MEDIAN_SPEND_PER_TRANSACTION, MEDIAN_SPEND_PER_CUSTOMER
FROM
FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE
WHERE category_tags like '%Burger%';



---Step 3-3: UNION 2 tables together 
SELECT LOCATION_NAME, REGION, POSTAL_CODE, STREET_ADDRESS, RAW_TOTAL_SPEND, RAW_NUM_TRANSACTIONS, RAW_NUM_CUSTOMERS, ONLINE_SPEND, MEDIAN_SPEND_PER_TRANSACTION, MEDIAN_SPEND_PER_CUSTOMER
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE

UNION

SELECT LOCATION_NAME, REGION, POSTAL_CODE, STREET_ADDRESS, RAW_TOTAL_SPEND, RAW_NUM_TRANSACTIONS, RAW_NUM_CUSTOMERS, ONLINE_SPEND, MEDIAN_SPEND_PER_TRANSACTION, MEDIAN_SPEND_PER_CUSTOMER
FROM
FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE
WHERE category_tags like '%Burger%';


-----------------------------------------------------------------------
-- Step 4 Create Snowsight dashboard 

--- Step 4-1 Customer Spend by Location v.s. Competition

SELECT LOCATION_NAME, REGION,POSTAL_CODE, RAW_TOTAL_SPEND
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE

UNION

SELECT LOCATION_NAME, REGION, POSTAL_CODE, RAW_TOTAL_SPEND
FROM
FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE
WHERE category_tags like '%Burger%';


--- Step 4-2 Number of customer by location vs competition 

SELECT LOCATION_NAME, REGION,POSTAL_CODE, RAW_NUM_CUSTOMERS
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE

UNION

SELECT LOCATION_NAME, REGION, POSTAL_CODE, RAW_NUM_CUSTOMERS
FROM
FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE
WHERE category_tags like '%Burger%';

--- Step 4-3 ONLINE SPEND by location vs competition 

SELECT LOCATION_NAME, REGION,POSTAL_CODE, ONLINE_SPEND
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE

UNION

SELECT LOCATION_NAME, REGION, POSTAL_CODE,ONLINE_SPEND
FROM
FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE
WHERE category_tags like '%Burger%';


--- Step 4-4 Add Heatgrid chart compare median spend per transaction , focus on top3 locations
SELECT LOCATION_NAME, REGION,POSTAL_CODE,MEDIAN_SPEND_PER_TRANSACTION
FROM THERAREBURGER.PUBLIC.MONTHLY_REVENUE
WHERE postal_CODE in ('10036','10019', '10001')
UNION

SELECT LOCATION_NAME, REGION, POSTAL_CODE,MEDIAN_SPEND_PER_TRANSACTION
FROM
FREE_SAMPLE_CROSS_SHOPPING_INSIGHTS__NYC_RESTAURANTS.PUBLIC.SPEND_CROSS_SHOPPING_SAMPLE
WHERE category_tags like '%Burger%' and postal_CODE in ('10036','10019', '10001');







